// <auto-generated />
namespace GarryBoats.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updted));
        
        string IMigrationMetadata.Id
        {
            get { return "202105111144417_updted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
